# Generated by Django 3.1.4 on 2021-01-01 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('IdCategorie', models.AutoField(primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('DateCreation', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('IdArticle', models.AutoField(primary_key=True, serialize=False)),
                ('Libelle', models.CharField(max_length=255)),
                ('Details', models.CharField(max_length=255)),
                ('PrixUnitaire', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='entrer un prix valide')),
                ('DateCreation', models.DateField()),
                ('IdCategorie', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ArticlesApp.categories')),
            ],
        ),
    ]
